apiVersion: v1
kind: Service
metadata: 
  name: gruappfrontendservice
spec:
  selector:
    app: gruappfrontendlabel
  type: LoadBalancer
  ports:
    - name: gruappfrontendport
      port: 5000
      targetPort: 5000
  externalIPs:
    - 192.168.49.2
